server:
  name: blah.com
  host: 127.0.0.1
  port: 5555
dirs:
  templates: ./templates
  static: ./static
auth:
  username: user
  password: pass
mail:
  host: mail.example.com
  port: 25
  username: foo@bar.com
  password: foobar
  tls: true
  from: foo@bar.com
  to:
    - foo@bar.com
